// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrebrlmzespaiyrgvnae.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFyZWJybG16ZXNwYWl5cmd2bmFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTExOTk5MTksImV4cCI6MjA2Njc3NTkxOX0.T6oZ9k2MaygnOYVK7Qn73UFFXEv7Qoj-4md0u4vE7lU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);