// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gycsxuqegpgreackwpoa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd5Y3N4dXFlZ3BncmVhY2t3cG9hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI4MzI1MjQsImV4cCI6MjA3ODQwODUyNH0.5RiyMKhMqpDPDi4bM1jBNiQ_zdkf6gIKfSs_a7WoNYE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
